{% set name = "photochem" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Nicholaswogan/photochem/archive/v{{ version }}.tar.gz
  sha256: 2b82c0355e01e9d5d790ca4387b6518431b94fd8aa940af693425a7dc1a62769

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - fypp                                   # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - make
    - cmake
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - scikit-build
    - numpy
    - cython
    - ninja
    - pkgconfig
    - zlib
    - hdf5 <=1.14.3
    - fypp
    - libblas
    - libcblas
    - liblapack
  run:
    - python
    - photochem_clima_data ==0.2.0
    - scipy
    - pyyaml
    - numba
    - h5py
    - astropy
    - threadpoolctl
    - blis      # [linux]

test:
  imports:
    - photochem
    - photochem.clima
    - photochem.equilibrate

about:
  home: https://github.com/Nicholaswogan/photochem
  license: GPL-2.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: A chemical model of planetary atmospheres

extra:
  recipe-maintainers:
    - Nicholaswogan
